### ISSUE TITLE
[BUG] 拖动子节点时防重叠失效

### ISSUE THREAD

**Issue by H1DDENADM1N** [LiRenTech/visual-file-qt#2]
复现效果如图：

![PixPin_2024-07-29_08-03-03](https://github.com/user-attachments/assets/e34503e3-26d5-4df4-bebc-4e95867f746a)

目录结构：

```txt
📁 爷/
├─📁 叔/
│ └─📁 子/
└─📁 父/
  └─📁 子/
```

**Comment by Littlefean** [comment]
感谢反馈，刚刚解决了。
