### ISSUE TITLE
[BUG] 碰撞位移算法不合理导致矩形交错严重时一个矩形进入另一个矩形内部

### ISSUE THREAD

**Issue by Misaka-17365** [LiRenTech/visual-file-qt#5]
例子：

https://github.com/user-attachments/assets/b33fcf4d-963a-47e7-ac8a-dc52e6ad9114

---

程序中使用的是：将被拖动的矩形的位移矢量旋转到两个矩形的中心点连线的方向上作为被碰撞开的矩形的位移矢量。

当两个矩形的中心点连线的方向与矩形运动的方向相差较大时，矩形会发生交叠，示例图如下：

![image](https://github.com/user-attachments/assets/56ccefcb-fb91-4cf6-8439-6cde369eedb3)

向上移动右侧矩形，绿色粗箭头为运动矢量；红色箭头为中心连线；绿色细箭头为左侧被碰撞的矩形的移动矢量。
很显然，在碰撞的方向上（y 方向），右侧矩形运动矢量（绿粗）的分量**大于**左侧矩形运动矢量（绿细）的分量，因此会出现图形交叠。

**Comment by Littlefean** [comment]
对，确实是这样，这个挤压排开方法其实是最好实现的偷懒方法，
刚刚更新了挤压算法到master分支，现在挤压方法造成的平移效果都是与坐标轴平行的了。
