### ISSUE TITLE
修改操作方式

### ISSUE THREAD

**Issue by mzq2306** [LiRenTech/visual-file-qt#9]
建议改为长按鼠标右键移动视野，鼠标中键按起来比较费劲，或者支持配置操作方式就更好了。

**Comment by zty012** [comment]
用wasd

**Comment by Littlefean** [comment]
> 用wasd

最开始我就是用的wasd，结果发现放在左屏辅助的时候，经常忘了点击一下窗口，导致把wasd写在了代码里，所以后来才出了中键移动。

目前打算等下把右键设置成和中键一样的效果，至于右键以后是不是可能会新出新的功能，到时候再说。这个issue先不关了吧。

**Comment by Littlefean** [comment]
目前1.2.0版本及以后已经支持了右键拖动的功能。
